import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "#f7fafd",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  audioCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    width: "100%",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 10,
    elevation: 7,
  },
  topRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  coverImage: {
    width: 200,
    height: 200,
    borderRadius: 13,
    backgroundColor: "#dde3ea",
    marginBottom: 16,
  },
  audioTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#1a2230",
    textAlign: "center",
    marginBottom: 2,
  },
  audioArtist: {
    fontSize: 13,
    color: "#9291b",
    textAlign: "center",
    marginBottom: 12,
  },
  progressBox: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: 18,
  },
  progressTime: {
    width: 38,
    textAlign: "right",
    fontSize: 12,
    color: "#7d869a",
  },
  progressBarOuter: {
    flex: 1,
    height: 3,
    backgroundColor: "#e1e7ef",
    marginHorizontal: 6,
    borderRadius: 2,
    overflow: "hidden",
  },
  progressBarInner: {
    height: "100%",
    backgroundColor: "#ff6542",
    borderRadius: 1,
  },
  audioControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "88%",
    marginBottom: 16,
  },
  playButton: {
    backgroundColor: "#ff6542",
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#ff6542",
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  queryCard: {
    width: "100%",
    borderRadius: 16,
    backgroundColor: "#ecf9fd",
    padding: 12,
    paddingTop: 13,
    marginTop: 18,
    alignItems: "flex-start",
  },
  queryLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#6db7d0",
    marginBottom: 6,
  },
  queryInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  queryInput: {
    fontSize: 13,
    color: "#19749a",
    minHeight: 28,
    flex: 1,
  },  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 18,
    elevation: 8,
    zIndex: 1002,
  },
  title: { fontSize: 17, fontWeight: "bold", marginBottom: 10, color: "#222" },
  listBox: { marginVertical: 4, marginBottom: 12 },
  listItem: { fontSize: 15, marginVertical: 2, color: "#222" },
  confirmBtn: {
    backgroundColor: "#ff6542",
    borderRadius: 9,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 18,
  },
  confirmText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  
  // MiniAudioPlayer 스타일
  miniPlayerWrap: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 4,
  },
  coverImg: {
    width: 40,
    height: 40,
    borderRadius: 6,
    marginRight: 12,
  },
  infoArea: {
    flex: 1,
    marginRight: 12,
  },
  title: {
    fontSize: 14,
    fontWeight: "600",
    color: "#222",
    marginBottom: 2,
  },
  subTitle: {
    fontSize: 12,
    color: "#666",
  },
});

