import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    topRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 19,
      paddingTop: 16,
      paddingBottom: 4,
      minHeight: 46,
    },
    topTitle: {
      fontWeight: "bold",
      fontSize: 19,
      color: "#191E28",
      letterSpacing: -0.5,
    },
    profileRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 19,
      marginTop: 6,
      marginBottom: 4,
    },
    avatarCircle: {
      width: 47,
      height: 47,
      marginRight: 14,
      borderRadius: 23.5,
      backgroundColor: "#EDF1F7",
      alignItems: "center",
      justifyContent: "center",
    },
    avatarInitial: {
      color: "#8E979F",
      fontWeight: "bold",
      fontSize: 18.5,
    },
    userName: {
      fontWeight: "700",
      fontSize: 15.5,
      color: "#181926",
      marginBottom: 2,
      letterSpacing: -0.1,
    },
    infoManage: {
      fontSize: 12.2,
      color: "#FF715A",
      marginTop: -1,
      fontWeight: "bold",
      letterSpacing: -0.2,
    },
    coinCard: {
      backgroundColor: "#F5F7FA",
      borderRadius: 12,
      marginHorizontal: 13,
      marginTop: 7,
      marginBottom: 8,
      paddingTop: 17,
      paddingBottom: 14,
      paddingHorizontal: 17,
    },
    coinLabel: {
      color: "#848B9D",
      fontWeight: "bold",
      fontSize: 12.2,
      letterSpacing: -0.1,
      marginBottom: 4,
      marginLeft: 1,
    },coinRow1: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    coinValue: {
      fontWeight: "bold",
      fontSize: 22,
      color: "#232528",
      letterSpacing: -0.5,
    },
    fillBtn: {
      backgroundColor: "#FF6A3D",
      borderRadius: 7,
      paddingHorizontal: 12,
      paddingVertical: 7,
      marginLeft: 6,
    },
    fillBtnTxt: {
      color: "#fff",
      fontWeight: "bold",
      fontSize: 13.5,
      letterSpacing: -0.2,
    },
    coinRow2: {
      flexDirection: "row",
      marginTop: 14,
      justifyContent: "space-between",
      alignItems: "center",
    },
    rewardBox: {
      marginLeft: 11,
      alignItems: "flex-end",
      flexShrink: 1,
    },
    rewardLabel: {
      color: "#858CA1",
      fontWeight: "bold",
      fontSize: 12.6,
    },
    rewardTouch: {
      // 스타일 추가
    },
    rewardGoTouch: {
      // 스타일 추가
    },
    rewardGo: {
      color: "#161926",
      fontWeight: "700",
      fontSize: 12.5,
    },rewardRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 11,
      paddingHorizontal: 1,
    },rewardArrow: {
      color: "#A6ADB8",
      fontWeight: "bold",
      fontSize: 12.4,
    },
    tabBar: {
      flexDirection: "row",
      marginTop: 12,
      marginBottom: 2,
      paddingHorizontal: 6,
      borderBottomWidth: 1.1,
      borderBottomColor: "#E9EEF1",
      backgroundColor: "#fff",
      minHeight: 34,
    },
    tabBtn: {
      marginRight: 18,
      alignItems: "center",
      paddingBottom: 8,
      minWidth: 41,
      position: "relative",
    },
    tabTxt: {
      color: "#ABB0BE",
      fontWeight: "700",
      fontSize: 14.6,
      letterSpacing: -0.25,
    },
    tabActive: {},
    tabActiveTxt: {
      color: "#222328",
    },
    tabUnderline: {
      position: "absolute",
      left: 3,
      right: 3,
      bottom: -4,
      height: 2,
      backgroundColor: "#202128",
      borderRadius: 7,
    },
    listCount: {
      color: "#ABB0BE",
      fontSize: 12.6,
      marginLeft: 20,
      marginTop: 21,
      fontWeight: "700",
      marginBottom: 1,
    },
    cardRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#fff",
      paddingVertical: 13,
      borderRadius: 13,
    },
    thumbSquare: {
      width: 44,
      height: 44,
      borderRadius: 8,
      backgroundColor: "#ECECEC",
      marginRight: 1,
    },
    cardTitle: {
      fontWeight: "900",
      fontSize: 14.5,
      color: "#181926",
      marginBottom: 1,
      letterSpacing: -0.2,
    },
    cardSub: {
      fontSize: 12.2,
      color: "#A6ADB8",
      fontWeight: "600",
      letterSpacing: -0.12,
    },
    artistAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 1,
      borderWidth: 2,
      borderColor: "#F3F6FC",
      backgroundColor: "#ECECEC",
    },
    artistName: {
      fontWeight: "800",
      fontSize: 14.2,
      color: "#232956",
      marginBottom: 2,
      letterSpacing: -0.06,
    },
    artistSub: {
      fontSize: 12,
      color: "#6D7689",
      fontWeight: "600",
      letterSpacing: -0.1,
    },
    followBtnFilled: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#EEF4FD",
      borderRadius: 14,
      paddingHorizontal: 13,
      paddingVertical: 6.5,
    },
    followTxtFilled: {
      fontWeight: "800",
      fontSize: 13,
      color: "#0F172A",
      marginLeft: 5,
      letterSpacing: -0.13,
    },
    noteCard: {
      borderRadius: 15,
      padding: 15,
      backgroundColor: "#A9C6BB",
      marginBottom: 1,
      minHeight: 108,
      marginTop: 2,
    },
    noteCardTop: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    noteThumb: {
      width: 33,
      height: 33,
      borderRadius: 7,
      backgroundColor: "#fff",
    },
    noteTitle: {
      color: "#fff",
      fontWeight: "900",
      fontSize: 13.5,
      letterSpacing: -0.15,
    },
    noteArtist: {
      color: "#F9FAFD",
      fontSize: 10.8,
      fontWeight: "700",
      marginTop: 1,
    },
    noteQuestion: {
      color: "#fff",
      fontWeight: "800",
      fontSize: 12.7,
      marginTop: 2,
      marginBottom: 7,
      lineHeight: 19,
    },
    noteRowBottom: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 1,
    },
    noteMeta: {
      color: "#FCFCFF",
      fontSize: 11.3,
      fontWeight: "700",
      letterSpacing: -0.12,
    },
    hr: {
      height: 1,
      backgroundColor: "#F1F1F6",
    },
  });
  