import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#ededed",
  },
  thumbnail: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: "#ececec",
  },
  metaBox: { flex: 1, marginLeft: 10 },
  title: {
    fontSize: 15,
    fontWeight: "600",
    color: "#222",
  },
  artist: {
    fontSize: 13,
    color: "#999",
    marginTop: 2,
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  slideHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#ddd",
    borderRadius: 2,
    alignSelf: "center",
    marginVertical: 8,
  },
  infoText: {
    marginHorizontal: 16,
    marginTop: 4,
    color: "#9db0b9",
    fontSize: 12,
    textAlign: "center",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  chatList: {
    flex: 1,
    marginBottom: 2,
  },
  chatContentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    paddingTop: 6,
  },
  bubble: {
    padding: 15,
    borderRadius: 16,
    maxWidth: "80%",
    marginVertical: 5,
    position: "relative",
  },
  curiBubble: {
    backgroundColor: "#f3f3f3",
    alignSelf: "flex-start",
  },
  userBubble: {
    backgroundColor: "#ff5b55",
    alignSelf: "flex-end",
  },
  shareBtn: {
    position: "absolute",
    left: 12,
    bottom: 10,
    backgroundColor: "#fff8f7",
    borderRadius: 8,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  suggestedQuestionsContainer: {
    backgroundColor: "#fff",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#ededed",
  },
  suggestedHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 8,
    gap: 6,
  },
  suggestedHeaderText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
  },
  easyQRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    gap: 8,
    flexWrap: "wrap",
  },
  easyQBtn: {
    backgroundColor: "#f7f7f7",
    borderRadius: 18,
    borderColor: "#efefef",
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 7,
    marginBottom: 6,
  },
  easyQText: {
    color: "#707987",
    fontSize: 13,
  },
  bottomBox: {
    flexDirection: "row",
    alignItems: "center",
    padding: 13,
    borderTopWidth: 1,
    borderColor: "#eaeaea",
    backgroundColor: "#fff",
  },
  input: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#222",
    borderWidth: 1,
    borderColor: "#eee",
    marginRight: 9,
  },
  countSendBtnGroup: {
    flexDirection: "row",
    alignItems: "center",
  },
  charCount: {
    color: "#c7c7c7",
    fontSize: 13,
    marginRight: 6,
  },
  sendBtn: {
    backgroundColor: "#ff5b55",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
});
