import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    centerFill: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#fff" },
    topActions: { flexDirection: "row", justifyContent: "space-between", padding: 16, alignItems: "center" },
    actionIcon: { fontSize: 20 },
    headerImage: { width: "100%", height: 220, resizeMode: "cover" },
    infoBox: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16, borderBottomWidth: 1, borderColor: "#eee", gap: 10 },
    row: { flexDirection: "row", alignItems: "center", gap: 12 },
    avatar: { width: 44, height: 44, borderRadius: 22 },
    name: { fontSize: 16, fontWeight: "bold" },
    meta: { fontSize: 12, color: "#777", marginTop: 2 },
    followBtn: { borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8 },
    followTxt: { color: "#fff", fontWeight: "700" },
    intro: { color: "#333", lineHeight: 20, fontSize: 14 },
    moreLink: { color: "#007AFF", marginTop: 6, fontWeight: "600" },
    tabRow: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#eee" },
    tabItem: { flex: 1, alignItems: "center", paddingVertical: 12 },
    tabText: { color: "#666", fontWeight: "600" },
    tabActive: { borderBottomWidth: 2, borderBottomColor: "#000" },
    tabTextActive: { color: "#000", fontWeight: "bold" },
    workRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderColor: "#f4f4f4", gap: 12 },
    workThumb: { width: 60, height: 60, borderRadius: 8, backgroundColor: "#eee" },
    workTitle: { fontWeight: "700" },
    workSub: { color: "#666", marginTop: 2 },
    exCard: { marginTop: 16, marginHorizontal: 16, padding: 16, borderRadius: 12, backgroundColor: "#FAFAFA", borderColor: "#eee", borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 12 },
    exBadge: { color: "#FF5A5F", fontSize: 12, marginBottom: 4, fontWeight: "700" },
    exTitle: { fontWeight: "bold", fontSize: 16 },
    exMeta: { color: "#888", marginTop: 4 },
    exThumb: { width: 64, height: 64, borderRadius: 8, backgroundColor: "#eee" },
    emptyBox: { alignItems: "center", justifyContent: "center", paddingVertical: 32 },
    modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.25)", alignItems: "center", justifyContent: "center", padding: 20 },
    modalSheet: { width: "100%", maxWidth: 520, backgroundColor: "#fff", borderRadius: 12, padding: 16 },
    modalTitle: { fontSize: 16, fontWeight: "800", marginBottom: 8 },
    modalBody: { color: "#333", lineHeight: 22, marginBottom: 12 },
    modalBtn: { alignSelf: "flex-end", backgroundColor: "#111", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8 },
    modalBtnTxt: { color: "#fff", fontWeight: "700" },
  });
  